# Stub CRD for OpenShift Infrastructure API
# Required for cert-manager-operator to function on non-OpenShift clusters
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: infrastructures.config.openshift.io
spec:
  group: config.openshift.io
  names:
    kind: Infrastructure
    listKind: InfrastructureList
    plural: infrastructures
    singular: infrastructure
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
          status:
            type: object
            properties:
              controlPlaneTopology:
                type: string
              infrastructureTopology:
                type: string
              platform:
                type: string
              platformStatus:
                type: object
